param([ValidateSet('FindPaths','Install')][string]$Action='Install')
$ErrorActionPreference='Stop'
$root=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$catalog=Join-Path $root 'catalog\catalog.json'
function SteamPaths { $out=@(); $roots=@('HKCU:\Software\Valve\Steam','HKLM:\SOFTWARE\WOW6432Node\Valve\Steam','HKLM:\SOFTWARE\Valve\Steam'); foreach($r in $roots){try{$p=(Get-ItemProperty $r -Name SteamPath -ErrorAction Stop).SteamPath;if($p){$out+=$p}}catch{}}; $out|Select-Object -Unique }
function Find-AC { $found=@(); foreach($s in (SteamPaths)){ $libs=@($s);$vf=Join-Path $s 'steamapps\libraryfolders.vdf';if(Test-Path $vf){$libs+=(Select-String -Path $vf -Pattern '"path"\s+"([^"]+)"' -AllMatches|%{$_.Matches|%{$_.Groups[1].Value -replace '\\\\','\\'}})};foreach($l in ($libs|select -Unique)){ $p=Join-Path $l 'steamapps\common\assettocorsa';if(Test-Path (Join-Path $p 'content')){$found+=$p}}};$found|select -Unique }
function Choose-Path { $ps=@(Find-AC);if($ps.Count){Write-Host "Assetto Corsa paths:" -ForegroundColor Cyan;for($i=0;$i -lt $ps.Count;$i++){Write-Host "[$($i+1)] $($ps[$i])"};$n=Read-Host 'Choose path number';$idx=0;if([int]::TryParse($n,[ref]$idx)-and $idx -ge 1 -and $idx -le $ps.Count){return $ps[$idx-1]}};return Read-Host 'Enter Assetto Corsa root path' }
if($Action -eq 'FindPaths'){ $p=@(Find-AC);if($p.Count){$p|%{Write-Host $_ -ForegroundColor Green}}else{Write-Host 'No Steam installation found.' -ForegroundColor Yellow};pause;exit }
try{$data=Get-Content $catalog -Raw|ConvertFrom-Json;$mods=@($data.mods);for($i=0;$i -lt $mods.Count;$i++){Write-Host "[$($i+1)] $($mods[$i].name) | $($mods[$i].category) | $($mods[$i].version)"};$n=Read-Host 'Mod number';$m=$mods[[int]$n-1];if(!$m){throw 'Invalid mod'};$dest=Choose-Path;$tmp=Join-Path $env:TEMP ('uhm_'+[guid]::NewGuid());New-Item $tmp -ItemType Directory|Out-Null;$file=Join-Path $tmp ([IO.Path]::GetFileName(([uri]$m.downloadUrl).AbsolutePath));Write-Host 'Downloading...' -ForegroundColor Cyan;curl.exe -L --fail --retry 2 -o $file $m.downloadUrl;if(!(Test-Path $file)){throw 'Download failed'};$hash=Get-FileHash $file -Algorithm SHA256;if($m.sha256 -and $hash.Hash.ToLower() -ne $m.sha256.ToLower()){throw 'SHA-256 mismatch'};$extract=Join-Path $tmp 'extract';New-Item $extract -ItemType Directory|Out-Null;$seven=@("$env:ProgramFiles\7-Zip\7z.exe","${env:ProgramFiles(x86)}\7-Zip\7z.exe")|where{Test-Path $_}|select -First 1;if($m.password){$arg="-p$($m.password)"}else{$arg='-p'};if($file -match '\.(rar|7z)$' -and $seven){& $seven x $file "-o$extract" $arg -y}else{tar.exe -xf $file -C $extract};if($LASTEXITCODE -ne 0){throw 'Extraction failed'};$items=Get-ChildItem $extract -Recurse -File;foreach($x in $items){$rel=$x.FullName.Substring($extract.Length).TrimStart('\');if($rel -match '^\.\.' -or [IO.Path]::IsPathRooted($rel)){throw 'Unsafe archive path'}};Write-Host 'Installing...' -ForegroundColor Cyan;Copy-Item (Join-Path $extract '*') $dest -Recurse -Force;Write-Host "Installed: $($m.name)" -ForegroundColor Green}catch{Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red}finally{if($tmp -and (Test-Path $tmp)){Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue};pause}
